DECLARE @Name VARCHAR(100)
DECLARE @SQL VARCHAR(MAX)
DECLARE C1 CURSOR READ_ONLY FOR
select name FROM
(SELECT ROW_NUMBER() OVER(ORDER BY name) as RN,name from sys.tables where name LIKE 'sdf%') AS T
ORDER BY NAME
--WHERE T.RN BETWEEN 20 AND 40
DECLARE @T AS TABLE(T VARCHAR(512),CNT INT)

OPEN C1
FETCH NEXT FROM C1 INTO @NAME 

WHILE @@FETCH_STATUS=0
BEGIN



SET @SQL='SELECT '''+@Name+''' as TableName,count(*) as cnt FROM '+@Name

INSERT @T(T,CNT)
EXEC(@SQL)
print @sql


FETCH NEXT FROM C1 INTO @NAME
END
SELECT * FROM @T

CLOSE C1
DEALLOCATE C1


